#Logging
logging.config: classpath:logback.xml

spring:
  main:
    allow-bean-definition-overriding: false
  jackson:
    default-property-inclusion: NON_NULL
    serialization:
      write-dates-as-timestamps: true
      write-date-keys-as-timestamps: true
      write-durations-as-timestamps: true
      write-enums-using-to-string: false
      FAIL_ON_EMPTY_BEANS: false
  datasource:
    url: jdbc:postgresql://localhost:5432/core_finance_userprofile
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-test-query: SELECT 1
      maximum-pool-size: 10 # Adjust as needed
      minimum-idle: 2
      idle-timeout: 30000
      pool-name: userprofile_service_pool
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: validate
      show-sql: true
      generate-ddl: false
  # Liquibase settings
  liquibase:
    change-log: classpath:db/changelog/sql-changelog.xml
    drop-first: false
    enabled: true
    contexts: development
tech:
  corefinance:
    app:
      converter:
        local-date-to-string: true
        local-date-time-to-string: true
        zoned-date-time-to-string: true
        zoned-date-time-to-local-date-time: true
        zoned-date-time-to-date: true
    common:
      filter-ordered:
        authen-filter: 0
      enabled:
        async: true
        simple-version: true
        property-encryption: true
        auto-response-encoding: true
        trace-id-filter: true
        tenant: false
    log:
      enabled:
        services: true
        repositories: true
        api: true
    security:
      internal-api-key: No-key
      # Json Web Token
      jwt:
        expiration: 3600
        login-mode: SINGLE_LOGIN_PER_APP
        enabled:
          common: true
      public-key: classpath:public_key.der
      private-key:
      no-authen-urls:
        - /
        - /void
        - /parserConfigurationException
        - /throwable
        - /test/api/*
      permission:
        default-control: ALLOWED
      authorize-check: true
      scan-controllers-actions: true
      ignore-controller-scan:
        - .springframework.
        - .springdoc.
        - .test.
    encryption:
      plain: test
      encoded: ENC(O5MFWIMMOz+V3iItOVY60g==)
    initial:
      name-separator: _
      version-separator: .
      data-regex:
        permission:
          file-name-regex: classpath:initial/*permissions*.json
          replace-if-existed: true
        internal-api:
          file-name-regex: classpath:initial/*internal_api*.json
          replace-if-existed: true
export:
  format:
    date: yyyy/MM/dd
    datetime: yyyy/MM/dd HH:mm:ss
jasypt:
  encryptor:
    password: password
    # algorithm: PBEWithHmacSHA512AndAES_256
    algorithm: PBEWithMD5AndDES
    salt-generator-class-name: org.jasypt.salt.RandomSaltGenerator
    # provider-class-name: com.sun.crypto.provider.SunJCE
    provider-name: SunJCE
    string-output-type: base64
    key-obtention-iterations: 1000
    pool-size: 1