#Logging
logging.config: classpath:logback.xml
server.port: 8080

spring:
  main:
    allow-bean-definition-overriding: false
  jackson:
    default-property-inclusion: NON_NULL
    serialization:
      write-dates-as-timestamps: true
      write-date-keys-as-timestamps: true
      write-durations-as-timestamps: true
      write-enums-using-to-string: false
      FAIL_ON_EMPTY_BEANS: false
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:core_finance_userprofile}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}
    hikari:
      connection-test-query: SELECT 1
      maximum-pool-size: ${DB_MAX_CONNECTIONS:10}
      minimum-idle: ${DB_MIN_CONNECTIONS:2}
      idle-timeout: 30000
      pool-name: userprofile_service_pool
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: validate
      show-sql: true
      generate-ddl: false
  # Liquibase settings
  liquibase:
    change-log: classpath:db/changelog/sql-changelog.xml
    drop-first: false
    enabled: true
    contexts: development
tech:
  corefinance:
    app:
      converter:
        local-date-to-string: true
        local-date-time-to-string: true
        zoned-date-time-to-string: true
        zoned-date-time-to-local-date-time: true
        zoned-date-time-to-date: true
    common:
      filter-ordered:
        authen-filter: 0
      enabled:
        async: true
        simple-version: true
        property-encryption: true
        auto-response-encoding: true
        trace-id-filter: true
        tenant: false
    log:
      enabled:
        services: true
        repositories: true
        api: true
    security:
      internal-api-key: No-key
      # Json Web Token
      jwt:
        expiration: 3600
        login-mode: SINGLE_LOGIN_PER_APP
        enabled:
          common: true
        max-login-fail-allowed: 3
      public-key: classpath:public_key.der
      private-key: classpath:private_key.der
      no-authen-urls:
        - /
        - /void
        - /parserConfigurationException
        - /throwable
        - /test/api/*
      permission:
        default-control: ALLOWED
      authorize-check: true
      scan-controllers-actions: true
      ignore-controller-scan:
        - .springframework.
        - .springdoc.
        - .test.
      url-cors:
        cors-configurations:
          - url-pattern: /v3/api-docs/*
            allowed-origins:
              - http://localhost:4200
            allowed-methods:
              - GET
            allowed-headers: '*'
          - url-pattern: /**
            allowed-origins: '*'
            allowed-methods:
              - GET
              - PUT
              - OPTIONS
              - DELETE
              - POST
              - PATCH
            allowed-headers: '*'
    encryption:
      plain: test
      encoded: ENC(O5MFWIMMOz+V3iItOVY60g==)
export:
  format:
    date: yyyy/MM/dd
    datetime: yyyy/MM/dd HH:mm:ss
jasypt:
  encryptor:
    password: password
    # algorithm: PBEWithHmacSHA512AndAES_256
    algorithm: PBEWithMD5AndDES
    salt-generator-class-name: org.jasypt.salt.RandomSaltGenerator
    # provider-class-name: com.sun.crypto.provider.SunJCE
    provider-name: SunJCE
    string-output-type: base64
    key-obtention-iterations: 1000
    pool-size: 1

management:
  server:
    port: ${server.port}
  endpoints:
    web:
      base-path: /actuator
      enabled: true
      exposure.include: '*'